driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
  - name: debian-8.6
  - name: fedora-25
  - name: opensuse-13.2
  - name: opensuse-leap-42.1
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: freebsd-9.3
  - name: freebsd-10.3

suites:
- name: system_ruby
  run_list:
  - recipe[test]