driver:
  name: vagrant

provisioner:
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: fedora-25
  - name: debian-8
  - name: debian-9
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
- name: gem
  run_list: recipe[test::gem]
  includes: [centos-7]
- name: global
  run_list: recipe[test::global]
- name: system_install
  run_list: recipe[test::system_install]
  includes: [centos-7]
- name: user_install
  run_list: recipe[test::user_install]
  includes: [centos-7]
