version: 2.1

orbs:
  kitchen: sous-chefs/kitchen@1.0.0

workflows:
  kitchen:
    jobs:
      - kitchen/lint:
          name: lint
      - kitchen/dokken:
          name: global
          suite: global
          requires: [ lint ]
      - kitchen/dokken-single:
          name: system-install
          suite: system-install
          platform: centos-7
          requires: [ lint ]
      - kitchen/dokken-single:
          name: user-install
          suite: user-install
          platform: centos-7
          requires: [ lint ]
      - kitchen/dokken-single:
          name: gem
          suite: gem
          platform: centos-7
          requires: [ lint ]
      - kitchen/dokken-single:
          name: ruby-uninstall
          suite: ruby-uninstall
          platform: ubuntu-1804
          requires: [ lint ]
