---
jobs:
  final:
    docker:
      - image: bash:latest
    steps:
      - run:
          name: Finish cooking
          command: echo "Finished cooking"
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown
version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2
workflows:
  kitchen:
    jobs:
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery
      - kitchen/dokken-single:
          name: gem-centos-7
          suite: gem-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: global-debian-9
          suite: global-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: global-centos-6
          suite: global-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: global-centos-7
          suite: global-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: global-fedora-latest
          suite: global-fedora-latest
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: global-ubuntu-1604
          suite: global-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: global-ubuntu-1804
          suite: global-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: global-opensuse-leap
          suite: global-opensuse-leap
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ruby-uninstall-ubuntu-1804
          suite: ruby-uninstall-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: system-install-centos-7
          suite: system-install-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: user-install-centos-7
          suite: user-install-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: custom-group-install-centos-7
          suite: custom-group-install-centos-7
          requires: *lint_and_unit
      - final:
          requires:
            - gem-centos-7
            - global-debian-9
            - global-centos-6
            - global-centos-7
            - global-fedora-latest
            - global-ubuntu-1604
            - global-ubuntu-1804
            - global-opensuse-leap
            - ruby-uninstall-ubuntu-1804
            - system-install-centos-7
            - user-install-centos-7
            - custom-group-install-centos-7
